language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jean84matias/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jean84matias/docker-react npm run test